### ISSUE TITLE
Example throw an error

### ISSUE THREAD

**Issue by jjesusfilho** [michaeldorman/mapsapi#3]
When reproduced the example displayed in the readme, I got the following error:

`Error in sf::st_sf(alternative_id = i, summary = summary, distance_m = distance_m,  : 
  no simple features geometry column present`

**Comment by michaeldorman** [comment]
The reason for the error is that an empty document is returned; due to [new Google Maps API policy](https://developers.google.com/maps/billing/important-updates), starting from June 2018 the Google Maps API does not return any results when using without an API key. 

To keep using the `mapsapi` package, one needs to obtain a Google Maps API key, and pass it to the `key` parameter. 

I've now updated the README to reflect this.
